Implement our own wrapper around nats.Conn
overmindtech/sdp-go pull request #34
Opened 2023-01-09 18:02 UTC by DavidS-om

Since nats.EncodedConn is deprecated and we need more control around header management to inject opentelemetry propagation context.

Core piece is the sdp.EncodedConnection interface and sdp.EncodedConnectionImpl, which take care of propagating the otel trace context and protobuf marshaling.

Everything else is just for connecting all the dots after that change, like threading a ctx through all processing

2023-01-09 19:59 UTC, DavidS-om commented on connection.go
> +		var payload M = alloc()
I REALLY don't like it, but I couldn't find a better solution for allocating generic memory in a short search.  Any ideas?

2023-01-09 21:07 UTC, DavidS-om commented on connection.go
> +		var payload M = alloc()
since `proto.Message` is an interface, any hack I could come up with only returns `nil`.

2023-01-10 11:51 UTC, dylanratcliffe requested changes
I think we should have `Start()` handle context cancellation too, plus one question about a TODO

2023-01-10 12:20 UTC, DavidS-om commented on progress.go
> +func (rs *ResponseSender) Start(ctx context.Context, ec EncodedConnection, responderName string) {
:heavy_check_mark:

2023-01-10 12:23 UTC, DavidS-om commented on progress.go
> +			context.TODO(),
I was hoping to eventually get a ctx passed into `Done()`, but that didn't naturally happen, and I also couldn't find someone calling this in a quick search. Demoted it to Background now.

2023-01-10 14:56 UTC, dylanratcliffe approved these changes
Nice. `KillWithResponse` is a good change too

2023-01-10 14:57 UTC, merged